/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106989-gb033913d1c-20220524"
#endif /* AVUTIL_FFVERSION_H */
